# Generated by Django 4.2.28 on 2026-03-11 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_travelerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(choices=[('PASSPORT', 'Passport'), ('ID', 'National ID')], max_length=10)),
                ('issuanceDate', models.DateField()),
                ('expiryDate', models.DateField()),
                ('issuanceCountry', models.CharField(max_length=2)),
                ('issuanceLocation', models.CharField(blank=True, max_length=30, null=True)),
                ('documentNumber', models.CharField(max_length=30)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.travelerprofile')),
            ],
        ),
    ]
