# Generated by Django 4.2.28 on 2026-03-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_travelerdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerdocument',
            name='traveler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.travelerprofile'),
        ),
    ]
