# Generated by Django 4.2.27 on 2026-03-12 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amadeus_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('pnr', models.CharField(blank=True, default='', max_length=10)),
                ('airline_name', models.CharField(blank=True, default='', max_length=100)),
                ('origin', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=5)),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField()),
                ('stops', models.PositiveSmallIntegerField(default=0)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='EUR', max_length=5)),
                ('trip_type', models.CharField(default='oneway', max_length=10)),
                ('amadeus_response', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
