# Generated by Django 4.2.27 on 2026-03-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='checkin_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
